# Generated by Django 3.1.2 on 2020-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20201024_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='Title of the type')),
                ('type_image', models.ImageField(null=True, upload_to='static/img')),
            ],
        ),
    ]
