# Generated by Django 3.1.2 on 2020-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubadmin_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.TimeField(null=True, verbose_name='Hours'),
        ),
    ]
