# Generated by Django 3.1.2 on 2020-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20201105_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubadmin',
            name='rights',
            field=models.CharField(max_length=14, verbose_name='Rights'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='clubs.Club'),
        ),
    ]
