# Generated by Django 3.1.2 on 2020-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_clubtype_type_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtype',
            name='type_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Url to the page with list of clubs of such type (For example testUrl) '),
        ),
    ]
