# Generated by Django 3.1.2 on 2020-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20201107_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_logo',
            field=models.ImageField(default='static/img/no_image_found.png', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='clubtype',
            name='type_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Url to the page with list of clubs of such type (For example testUrl)'),
        ),
    ]
