# Generated by Django 3.1.2 on 2020-11-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20201107_1308'),
        ('clubs', '0008_auto_20201108_1547'),
    ]

    operations = [
    ]
