# Generated by Django 3.1.2 on 2020-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_merge_20201110_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, choices=[('Sun.', 'Sunday'), ('Mon.', 'Monday'), ('Tues.', 'Tuesday'), ('Wed.', 'Wednesday'), ('Thur.', 'Thursday'), ('Fri.', 'Friday'), ('Sat.', 'Saturday')], max_length=8, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('place', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('one_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('place', models.CharField(max_length=15)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='club',
            name='club_title',
            field=models.CharField(editable=False, max_length=200, verbose_name='Title of the club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_url',
            field=models.CharField(editable=False, max_length=200, verbose_name='Url of the club(For example testUrl)'),
        ),
        migrations.AlterField(
            model_name='clubtype',
            name='type_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Url to the page with list of clubs of such type (For example testUrl)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due_date'),
        ),
    ]
