# Generated by Django 3.1.2 on 2020-11-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_auto_20201110_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='one_time',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='clubs.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='participants',
            field=models.ManyToManyField(blank=True, to='clubs.Student'),
        ),
        migrations.AddField(
            model_name='onetimeevent',
            name='title',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=16),
        ),
    ]
