# Generated by Django 3.1.2 on 2020-11-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20201117_1353'),
        ('clubs', '0013_auto_20201110_1814'),
    ]

    operations = [
    ]
