# Generated by Django 3.1.3 on 2020-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20201110_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_title',
            field=models.CharField(max_length=200, verbose_name='Title of the club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_url',
            field=models.CharField(max_length=200, verbose_name='Url of the club(For example testUrl)'),
        ),
    ]
