# Generated by Django 3.1.2 on 2020-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_auto_20201110_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='week_day',
            field=models.IntegerField(choices=[('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday')]),
        ),
        migrations.AlterField(
            model_name='onetimeevent',
            name='date',
            field=models.DateField(),
        ),
    ]
