# Generated by Django 3.1.3 on 2020-11-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20201110_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.clubtype'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_title',
            field=models.CharField(editable=False, max_length=200, verbose_name='Title of the club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_url',
            field=models.CharField(editable=False, max_length=200, verbose_name='Url of the club(For example testUrl)'),
        ),
    ]
