# Generated by Django 3.1.2 on 2020-11-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20201121_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='week_day',
            field=models.IntegerField(choices=[(6, 'Sunday'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')]),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('attended', models.ManyToManyField(blank=True, to='clubs.Student')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.event')),
            ],
        ),
    ]
