# Generated by Django 3.1.3 on 2020-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_auto_20201122_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_title',
            field=models.CharField(max_length=200, verbose_name='Title of the club'),
        ),
    ]
