# Generated by Django 3.1.2 on 2020-11-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_auto_20201122_0851'),
        ('clubs', '0015_auto_20201121_1922'),
    ]

    operations = [
    ]
