# Generated by Django 3.1.2 on 2020-11-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_merge_20201122_1347'),
        ('clubs', '0017_merge_20201122_1739'),
    ]

    operations = [
    ]
