# Generated by Django 3.1.2 on 2020-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_title', models.CharField(max_length=200, verbose_name='Title of the club')),
                ('club_info', models.CharField(max_length=2000, verbose_name='Information of the club')),
                ('club_logo', models.ImageField(null=True, upload_to='static/img')),
                ('club_url', models.CharField(max_length=200, verbose_name='Url of the club(For example testUrl)')),
            ],
        ),
    ]
